#!/usr/bin/env bash
set -o xtrace
set -o errexit

ulimit -n 1024

OUTPUT_PATH="ci-secrets-cli.tar.gz"
CI_SECRETS_CLI_KEY="cii/ci-secrets-cli/cii-ci-secrets-cli_main.tar.gz"
CI_SECRETS_BUCKET="repository-archives"

CI_SECRETS_ROOT="/ci-secrets"
CI_SECRETS_BIN="${CI_SECRETS_ROOT}/ci-secrets-cli"

export AWS_REGION="us-west-2"
aws s3api get-object --bucket $CI_SECRETS_BUCKET --key $CI_SECRETS_CLI_KEY $OUTPUT_PATH

mkdir -p $CI_SECRETS_BIN
tar -zxpf $OUTPUT_PATH -C $CI_SECRETS_BIN
rm -rf $OUTPUT_PATH

CI_SECRETS_CLI="${CI_SECRETS_ROOT}/ci-secrets-cli/bin/launch/ci-secrets-cli"
$CI_SECRETS_CLI init-credentials-file --credential-fetcher "${CI_SECRETS_CLI} fetch-credentials" $CI_SECRETS_AWS_CREDENTIALS_FILE